### ISSUE TITLE
Stdin and tty is unavailable in docker-compose, even I turn them in docker-compose.yml file

### ISSUE THREAD

**Issue by RuofengX** [GedasFX/tmodloader#3]
## My docker-compose.yml file

```yaml
version: "3.8"

services:
  tmlserver:
    container_name: tmlserver
    image: gedasfx/tmodloader-server
    environment:
      - TMLSERVER_VERSION=0.11.8.8                    # Required; tModLoaderServer version
    volumes:
      - ./tModLoader_data:/data                       # Optional, volume is created for this regardless
      - ./tModLoader_server:/server                   # Optional, volume is created for this regardless
      - ./serverconfig.txt:/server/serverconfig.txt   # Recommended to use.
    ports:
      - "7777:7777"
    stdin_open: true  # I added this line
    tty: true  # and this line...
```

Stdin didn't work on my linux machine, let's say, type help or /help, there is no return.  
![NoReturn](https://user-images.githubusercontent.com/40327863/160376323-6d7fc104-0cd7-4260-8b32-5d58e95d743b.png)
